In [30]:
import pandas as pd

In [31]:
temp = pd.read_csv('Suggested Sensor Sets.csv')

In [32]:
temp = temp[['E+ Output Field', 'Sensor Set']]

In [33]:
temp = temp.iloc[1:185]

In [34]:
temp

                                       E+ Output Field Sensor Set
1                              cooling_electricity [W]       Rich
2                             electricity_facility [W]      Basic
3    whole_building_facility_total_hvac_electric_de...   Moderate
4           rooftop_supply_fan_fan_electric_energy [W]       Rich
5                                 fans_electricity [W]       Rich
..                                                 ...        ...
180             room_202_zone_mean_air_temperature [C]   Moderate
181             room_203_zone_mean_air_temperature [C]   Moderate
182             room_204_zone_mean_air_temperature [C]   Moderate
183             room_205_zone_mean_air_temperature [C]   Moderate
184             room_206_zone_mean_air_temperature [C]   Moderate

[184 rows x 2 columns]

In [35]:
sensor_group_dict = temp.set_index('E+ Output Field').to_dict()['Sensor Set']

In [42]:
# post processing

weather_list = ['AK_Fairbanks', 'FL_Miami', 'KY_Louisville', 'MN_Duluth', 'SAU_Riyadh', 'TN_Knoxville', 'VA_Richmond']

for weather in weather_list:
    temp = pd.read_csv(f'results/module_3/final_sensor_importance_{weather}.csv')
    temp['sensor group'] = temp['sensor'].map(sensor_group_dict)
    temp = temp[['sensor', 'sensor group', 'selected possibility']]
    temp.to_csv(f'results/module_3/postprocessed/final_sensor_importance_postprocessed_{weather}.csv', index = None)

In [41]:
temp

,sensor,sensor group,selected possibility
0,room_104_vav_reheat_damper_outlet_system_node_...,Rich,99
1,fans_electricity [W],Rich,99
2,room_204_vav_reheat_damper_outlet_system_node_...,Rich,98
3,rooftop_supply_fan_fan_electric_energy [W],Rich,96
4,interiorlights_electricity [W],Moderate,96
...,...,...,...
61,room_102_supply_inlet_system_node_current_dens...,Unlikely,4
62,environment_site_rain_status [],Basic,3
63,{38113ce7-41ec-4cfc-9439-9e0eb1e4167e}_system_...,Unlikely,3
64,node_4_system_node_current_density_volume_flow...,Unlikely,2
65,node_23_system_node_current_density_volume_flo...,Unlikely,1